steps:
- id: test
  name: "python:3.7"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip3 install -r ./gcb/app/requirements.txt
      python3 ./gcb/app/test.py ./gcb/app/

- id: build
  name: "gcr.io/cloud-builders/docker"
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/which-gcp-app:${SHORT_SHA}'
    - './gcb/app'

- id: push
  name: "gcr.io/cloud-builders/docker"
  args:
    - 'push'
    - 'gcr.io/${PROJECT_ID}/which-gcp-app:${SHORT_SHA}'

- id: kustomize-dev
  name: "gcr.io/${PROJECT_ID}/kustomize"
  entrypoint: bash
  args:
    - '-c'
    - |
      kustomize build "./gcb/overlays/dev" -o "/workspace/resources.yaml"
  env:
      - 'CLOUDSDK_COMPUTE_REGION=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=oregon'
      - 'GCLOUD_PROJECT=agmsb-k8s'

- id: gke-deploy
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
    - 'run'
    - '-f'
    - '/workspace/resources.yaml'
    - '--image=gcr.io/${PROJECT_ID}/which-gcp-app:${SHORT_SHA}'
    - '--label=commit-sha=${SHORT_SHA}'
    - '--location=us-west1'
    - '--cluster=oregon'