apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: gke-flask-app
build:
  artifacts:
  - image: gcr.io/agmsb-k8s/gke-flask-app
    context: app
deploy:
  kustomize:
    paths:
    - resources
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - overlays/dev
- name: prod
  deploy:
    kustomize:
      paths:
      - overlays/prod
