steps:
- id: build
  name: "gcr.io/cloud-builders/docker"
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/single-app:${SHORT_SHA}'
    - './gcb/single-app'

- id: push
  name: "gcr.io/cloud-builders/docker"
  args:
    - 'push'
    - 'gcr.io/${PROJECT_ID}/single-app:${SHORT_SHA}'

- id: kustomize-staging
  name: "gcr.io/${PROJECT_ID}/kustomize"j
  entrypoint: bash
  args:
    - '-c'
    - |
      kustomize build "./gcb/single-app/k8s/overlays/staging" -o "workspace/resources" && cat "workspace/resources/staging-deployment.yaml"
  env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=oregon'
      - 'GCLOUD_PROJECT=agmsb-k8s'

# - id: deploy
#   name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#     - 'run'