steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${PROJECT_ID}/pipeline:${SHORT_SHA}'
    - './gcb/single-app'
- name: "gcr.io/cloud-builders/docker"
  args:
    - 'push'
    - 'gcr.io/${PROJECT_ID}/pipeline:${SHORT_SHA}'