apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: flask
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
images:
- name: gcr.io/agmsb-k8s/gke-flask-app
  newTag: a62c31edb966096940b8bcfbf29565d90c684798
